package com.codingpixel.dedicatekitchen.helpers

object IntentParams {

    const val KITCHEN_ID: String = "kitchen_id"
    const val TITLE = "title"
    const val SHOW_TITLE = "showTitle"
    const val TOGGLE_OPTIOSN_LIST = "toggleOptionsList"
    const val TIME_SLOT = "timeSlot"
    const val FROM_DID_NOT_GET_CODE = "fromDidNotGetCode"
    const val SELECTED_MONTH = "selectedMonth"
    const val SELECTED_YEAR = "selectedYear"
    const val WEB_URL = "webUrl"
    const val CARD_STRIPE_ID = "stripe_id"
    const val CARD_ID = "card_id"
    const val TABLE_TRANSACTION_ID = "tableTransaction"
    const val MESSAGE = "message"
    const val LEFT_BUTTON_TEXT = "leftButtonText"
    const val RIGHT_BUTTON_TEXT = "rightButtonText"
    const val PRODUCTS = "product"
    const val CATEGORY = "category"
    const val OPTIONS = "options"
    const val CODE = "code"
    const val EMAIL = "email"
    const val TYPE = "type"
    const val SHOWTAXBOX = "showTaxBox"
    const val ORDERITEMS = "orderItems"
    const val PLACEORDER = "placeOrder"
    const val EDITORDER = "editOrder"
    const val TAG = "tag"
    const val KITCHEN = "selectedKitchen"
    const val TIME = "selectedTime"
    const val PAYMENT_TYPE = "paymentType"
    const val CARD_TOKEN = "cardToken"
    const val ORDER_DETAIL_HISTORY = "orderDetail"
    const val PRODUCT_ID = "productId"
    const val ORDER_PLACED = "orderPlaced"
    const val MEAL_PREP_TIME_SLOT_TO_SHOW = "meal_prep_time_slot"
    const val MEAL_PREP_TIME_SLOT_TO_SEND = "meal_prep_time_slot_to_send"
    const val MEAL_PREP_DATE = "meal_prep_date"
    const val MEAL_PREP_LOCATION_ID = "meal_prep_location_id"
    const val MEAL_PREP_LOCATION = "meal_prep_location"
    const val MEAL_PREP_ORDER_TYPE = "meal_prep_order_type"
    const val TAKEOUT = "takeout"
    const val DELIVERY = "delivery"
    const val ORDERID = "order_id"
    const val instantTakeoutTime = "instantTakeoutTime"
    const val CART_ITEM_P_KEY = "cartItemPKey"
    const val ORDERTYPE = "orderType"
    const val isMealPrep = "mealPrep"
    const val buyPackageAtCheckout = "buyPackageAtCheckout"
    const val fromViewMenu = "fromViewMenu"

    /*Edited By Usama*/
    const val CATEGORY_ID = "CATEGORY_ID"
    const val PRODUCT = "PRODUCT"
}
